
simulation:
    n_envs: 1000
    n_steps_for_env: 1000
    random_action: True
    mdp: False

scenario:
    navigation:
        shared_rew : False
        world_spawning_x: 0.5
        world_spawning_y: 0.5
        enforce_bounds: True
        continuous_actions: False
        seed: 42
        pos_shaping_factor: 0.0

    discovery:
        continuous_actions: False
        x_semidim: 0.5
        y_semidim: 0.5
        seed: 42

    flocking:
        continuous_actions: False
        seed: 42

    give_way:
        continuous_actions: False
        seed: 42

    balance:
        continuous_actions: False
        seed: 42

    dropout:
        continuous_actions: False
        seed: 42

    wheel:
        continuous_actions: False
        seed: 42

