
simulation:
    n_envs: 10
    n_steps_for_env: 1000
    random_action: True
    mdp: False

scenario:
    navigation:
        shared_rew : False
        x_semidim: 0.5
        y_semidim: 0.5
        continuous_actions: False
        seed: 42

    discovery:
        continuous_actions: False
        seed: 42

    flocking:
        continuous_actions: False
        seed: 42

    balance:
        continuous_actions: False
        seed: 42
