
'simulation_config':
  'task': 'navigation'
  'n_episodes': 2
  'n_agents': 4
  'max_steps_env': 1000
  'n_environments': 2
  'observability': 'mdp'
  'n_sensors': 8
  'continuous_actions': False
  'n_bins_discretization': 10
  'n_sensors_on': 2 # if None or > n_sensors = n_sensors
