
'simulation_config':
  'task': 'causality_vmas'
  'n_episodes': 1
  'n_agents': 4
  'max_steps_env': 5000
  'n_environments': 5
  'observability': 'mdp'
  'n_sensors': 8
  'continuous_actions': False
  'n_bins_discretization': 50
  'n_sensors_on': 1 # if None or > n_sensors = n_sensors
