x_semidim: 0.5
y_semidim: 0.5
n_rows: 500000
n_bins_considered: [5, 10, 15, 20, 30, 50, 100]
n_sensors_considered: [1, 3, 5, 8]
default_cd_algo: 'pc'
task: 'navigation'
dataframe_path: navigation/causal_knowledge/offline_ok/df_random_mdp_1000000.pkl
